name: Run batch

on:
  push:
    branches: [ master ]
  schedule:
    - cron: 1 * * * *

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    # - uses: actions/checkout@v2
    - uses: php-actions/composer@v6
      with:
        php_version: 7.1
        version: 1

    - name: Install dependencies
      run: composer update && composer install --prefer-dist --no-progress --no-suggest
    - name: Run batch
      run: php batch.php
      env:
        SLACK_API_TOKEN: ${{ secrets.SLACK_API_TOKEN }}
        SLACK_WEBHOOK_ENDPOINT: ${{ secrets.SLACK_WEBHOOK_ENDPOINT }}
        TITLE: ${{ secrets.TITLE }}
